### ISSUE TITLE
package 

### ISSUE THREAD

**Issue by Linzcarl** [sotiraslab/AgileFormer#4]
I encountered an issue while installing the package with "RuntimeError: Couldn't load custom C++ops. Recompile C++extension with: Python setup.py build_ext -- in-place". I understand that the version of torch vision needs to be greater than 0.3 to use ops, but the torch vision version that is compatible with CUDA 12.1+PyTorch 2.2 is 0.17. Can you please provide the complete package and version? thanks

**Comment by Linzcarl** [comment]
If I don't use tvdcn and mmcv the program runs fine

**Comment by peijieq** [comment]
@zl1216 Thank you for being interested in our work. I know the installation of some of the packages may be bumpy (I was also struggling at the very beginning). It seems that this error may occur due to tvdcn based on your later comments (correct me if I was wrong). In this case, I suggest building tvdcn from source, as what tvdcn suggests: https://github.com/inspiros/tvdcn/blob/master/README.md#from-source\. Would you please tell me which operating system you were using (Windows or Linux), and Whether did you install tvdcn from source or pip instll ? Could you also try the following code to check if tvdcn was successfully installed: 

```
import tvdcn

print('Library loaded successfully:', tvdcn.has_ops())
print('Compiled with Cuda:', tvdcn.with_cuda()
```

Here is the core package versions of my environment: 
torch==2.1.1+cu121
tvdcn==0.5.0
natten==0.15.0+torch210cu121
